apiVersion: v1
data:
  run.sh: ""
kind: ConfigMap
metadata:
  labels:
    app: mysql
    chart: mysql-0.10.1
    heritage: Tiller
    release: mysql
  name: mysql-test
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mysql
    chart: mysql-0.10.1
    heritage: Tiller
    release: mysql
  name: mysql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test-success
  labels:
    app: mysql
    chart: mysql-0.10.1
    heritage: Tiller
    release: mysql
  name: mysql-test
spec:
  containers:
  - command:
    - /tools/bats/bats
    - -t
    - /tests/run.sh
    image: mysql:5.7.14
    name: mysql-test
    volumeMounts:
    - mountPath: /tests
      name: tests
      readOnly: true
    - mountPath: /tools
      name: tools
  initContainers:
  - command:
    - bash
    - -c
    - |
      set -ex
      # copy bats to tools dir
      cp -R /usr/local/libexec/ /tools/bats/
    image: dduportal/bats:0.4.0
    name: test-framework
    volumeMounts:
    - mountPath: /tools
      name: tools
  restartPolicy: Never
  volumes:
  - configMap:
      name: mysql-test
    name: tests
  - emptyDir: {}
    name: tools
---
apiVersion: v1
data:
  mysql-password: N1JuQW96enQwUw==
  mysql-root-password: RVh0dmEyYWJuSw==
kind: Secret
metadata:
  labels:
    app: mysql
    chart: mysql-0.10.1
    heritage: Tiller
    release: mysql
  name: mysql
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
    chart: mysql-0.10.1
    heritage: Tiller
    release: mysql
  name: mysql
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: mysql
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mysql
    chart: mysql-0.10.1
    heritage: Tiller
    release: mysql
  name: mysql
spec:
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-root-password
              name: mysql
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-password
              name: mysql
        - name: MYSQL_USER
          value: ""
        - name: MYSQL_DATABASE
          value: ""
        image: mysql:5.7.14
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data
      initContainers:
      - command:
        - rm
        - -fr
        - /var/lib/mysql/lost+found
        image: busybox:1.25.0
        imagePullPolicy: IfNotPresent
        name: remove-lost-found
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mysql
